<?php

/**
 * BaserpgPlayer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $grid_space_id
 * @property rpgGridSpace $GridSpace
 * 
 * @method string       getName()          Returns the current record's "name" value
 * @method integer      getGridSpaceId()   Returns the current record's "grid_space_id" value
 * @method rpgGridSpace getGridSpace()     Returns the current record's "GridSpace" value
 * @method rpgPlayer    setName()          Sets the current record's "name" value
 * @method rpgPlayer    setGridSpaceId()   Sets the current record's "grid_space_id" value
 * @method rpgPlayer    setGridSpace()     Sets the current record's "GridSpace" value
 * 
 * @package    rpg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id$
 */
abstract class BaserpgPlayer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rpg_player');
        $this->hasColumn('name', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('grid_space_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('rpgGridSpace as GridSpace', array(
             'local' => 'grid_space_id',
             'foreign' => 'id'));
    }
}