<?php

/**
 * BaserpgTerrain
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property boolean $traversable
 * @property string $class
 * @property Doctrine_Collection $GridSpaces
 * 
 * @method boolean             getTraversable() Returns the current record's "traversable" value
 * @method string              getClass()       Returns the current record's "class" value
 * @method Doctrine_Collection getGridSpaces()  Returns the current record's "GridSpaces" collection
 * @method rpgTerrain          setTraversable() Sets the current record's "traversable" value
 * @method rpgTerrain          setClass()       Sets the current record's "class" value
 * @method rpgTerrain          setGridSpaces()  Sets the current record's "GridSpaces" collection
 * 
 * @package    rpg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id$
 */
abstract class BaserpgTerrain extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rpg_terrain');
        $this->hasColumn('traversable', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('class', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('rpgGridSpace as GridSpaces', array(
             'local' => 'id',
             'foreign' => 'terrain_id'));
    }
}