<?php

/**
 * BaserpgPlayer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $current_unit_id
 * @property rpgUnit $CurrentUnit
 * @property Doctrine_Collection $Units
 * 
 * @method string              getName()            Returns the current record's "name" value
 * @method integer             getCurrentUnitId()   Returns the current record's "current_unit_id" value
 * @method rpgUnit             getCurrentUnit()     Returns the current record's "CurrentUnit" value
 * @method Doctrine_Collection getUnits()           Returns the current record's "Units" collection
 * @method rpgPlayer           setName()            Sets the current record's "name" value
 * @method rpgPlayer           setCurrentUnitId()   Sets the current record's "current_unit_id" value
 * @method rpgPlayer           setCurrentUnit()     Sets the current record's "CurrentUnit" value
 * @method rpgPlayer           setUnits()           Sets the current record's "Units" collection
 * 
 * @package    rpg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id$
 */
abstract class BaserpgPlayer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rpg_player');
        $this->hasColumn('name', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('current_unit_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('rpgUnit as CurrentUnit', array(
             'local' => 'current_unit_id',
             'foreign' => 'id'));

        $this->hasMany('rpgUnit as Units', array(
             'local' => 'id',
             'foreign' => 'player_id'));
    }
}