<?php

/**
 * BaserpgGrid
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property Doctrine_Collection $GridSpaces
 * 
 * @method string              getTitle()      Returns the current record's "title" value
 * @method Doctrine_Collection getGridSpaces() Returns the current record's "GridSpaces" collection
 * @method rpgGrid             setTitle()      Sets the current record's "title" value
 * @method rpgGrid             setGridSpaces() Sets the current record's "GridSpaces" collection
 * 
 * @package    rpg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id$
 */
abstract class BaserpgGrid extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('rpg_grid');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('rpgGridSpace as GridSpaces', array(
             'local' => 'id',
             'foreign' => 'grid_id'));
    }
}