<?php

/**
 * rpgGrid
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    rpg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id$
 */
class rpgGrid extends BaserpgGrid
{
}
