<?php

/**
 * rpgPlayer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    rpg
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id$
 */
class rpgPlayer extends BaserpgPlayer
{
  public function getGridSpaces($radius = 1)
  {
    $grid_space = $this->GridSpace;
    
    return Doctrine_Query::create()
      ->from('rpgGridSpace')
      ->where('x >= ?', $grid_space->x - $radius)
      ->andWhere('x <= ?', $grid_space->x + $radius)
      ->andWhere('y >= ?', $grid_space->y - $radius)
      ->andWhere('y <= ?', $grid_space->y + $radius)
      ->orderBy('y DESC, x ASC')
      ->execute();
  }
  
  public function getLeft()
  {
    return Doctrine_Query::create()->from('rpgGridSpace')->where('x = ?', $this->GridSpace->x - 1)->andWhere('y = ?', $this->GridSpace->y)->fetchOne();
  }
  
  public function getRight()
  {
    return Doctrine_Query::create()->from('rpgGridSpace')->where('x = ?', $this->GridSpace->x + 1)->andWhere('y = ?', $this->GridSpace->y)->fetchOne();
  }
  
  public function getUp()
  {
    return Doctrine_Query::create()->from('rpgGridSpace')->where('x = ?', $this->GridSpace->x)->andWhere('y = ?', $this->GridSpace->y + 1)->fetchOne();
  }
  
  public function getDown()
  {
    return Doctrine_Query::create()->from('rpgGridSpace')->where('x = ?', $this->GridSpace->x)->andWhere('y = ?', $this->GridSpace->y - 1)->fetchOne();
  }
}
