<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/10/31 14:40:43

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=rpg',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
