rpgGrid:
  columns:
    title: string(255)

rpgGridSpace:
  columns:
    grid_id: integer
    terrain_id: integer
    x: integer
    y: integer
  relations:
    Grid:
      foreignAlias: GridSpaces
      local: grid_id
      class: rpgGrid
    Terrain:
      foreignAlias: GridSpaces
      local: terrain_id
      class: rpgTerrain

rpgTerrain:
  columns:
    traversable:
      type: boolean
      default: true
    class: string(255)

rpgPlayer:
  columns:
    name: string(10)
    current_unit_id: integer
  relations:
    CurrentUnit:
      foreignAlias: CurrentPlayer
      local: current_unit_id
      class: rpgUnit

rpgUnit:
  columns:
    name: string(10)
    player_id: integer
    grid_space_id: integer
    image: string(255)
  relations:
    GridSpace:
      foreignAlias: Players
      local: grid_space_id
      class: rpgGridSpace
    Player:
      foreignAlias: Units
      local: player_id
      class: rpgPlayer